# Generated by Django 2.2.19 on 2021-04-24 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField()),
                ('timestamp_utc', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('all_day', models.BooleanField(default=False)),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('command', models.TextField(blank=True)),
                ('website_title', models.TextField(blank=True)),
                ('website_url', models.TextField(blank=True)),
                ('acitvity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='memex.Activity')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='memex.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
