# Generated by Django 2.2.17 on 2021-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
