# Generated by Django 2.2.17 on 2021-02-21 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_highlight_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='notes.Tag'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='highlights', to='notes.Tag'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField()),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.Book')),
                ('highlight', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.Highlight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
